FROM node:24.14.1-alpine3.23

WORKDIR /app

# Copy only package files first for Docker layering optimization
COPY package.json package-lock.json* ./

# Install dependencies. Since it's only for development we use npm install instead of npm ci
RUN npm install

# Astro default port
EXPOSE 4321

# Run Astro
CMD ["npm", "run", "dev"]
